# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.19 is version 41
loaderVersion="[41,)"
# The license for your mod. This is mandatory and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/bdgmb2/mc-autoshutdown/issues"
# If the mods defined in this file should show as separate resource packs
showAsResourcePack=false

[[mods]]
modId="mcautoshutdown"
version="1.0.0.0"
displayName="Server AutoShutdown"
updateJSONURL=""
displayURL="https://bengiles.me"
logoFile=""
credits="N/A"
authors="Ben & Aaron Giles (https://bengiles.me)"
description="Automatically shuts down a Minecraft server when there are no players"
displayTest="IGNORE_ALL_VERSION"